export default [
  {
    time_zone_name: 'Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London',
    time_zone_value: 'GMT',
    localized_timezone_name: 'Europe/London',
    master_id: 1,
  },
  {
    time_zone_name: 'Monrovia, Reykjavik',
    time_zone_value: 'GMT',
    localized_timezone_name: 'Europe/London',
    master_id: 2,
  },
  {
    time_zone_name: 'Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    time_zone_value: 'GMT+01:00',
    localized_timezone_name: 'Europe/Budapest',
    master_id: 3,
  },
  {
    time_zone_name: 'Brussels, Copenhagen, Madrid, Paris',
    time_zone_value: 'GMT+01:00',
    localized_timezone_name: 'Europe/Paris',
    master_id: 4,
  },
  {
    time_zone_name: 'Sarajevo, Skopje, Warsaw, Zagreb',
    time_zone_value: 'GMT+01:00',
    localized_timezone_name: 'Europe/Warsaw',
    master_id: 5,
  },
  {
    time_zone_name: 'West Central Africa',
    time_zone_value: 'GMT+01:00',
    localized_timezone_name: 'Africa/Lagos',
    master_id: 6,
  },
  {
    time_zone_name: 'Amman',
    time_zone_value: 'GMT+02:00',
    localized_timezone_name: 'Asia/Amman',
    master_id: 7,
  },
  {
    time_zone_name: 'Beirut',
    time_zone_value: 'GMT+02:00',
    localized_timezone_name: 'Asia/Beirut',
    master_id: 8,
  },
  {
    time_zone_name: 'Cairo',
    time_zone_value: 'GMT+02:00',
    localized_timezone_name: 'Africa/Cairo',
    master_id: 9,
  },
  {
    time_zone_name: 'Harare, Pretoria',
    time_zone_value: 'GMT+02:00',
    localized_timezone_name: 'Africa/Johannesburg',
    master_id: 10,
  },
  {
    time_zone_name: 'Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
    time_zone_value: 'GMT+02:00',
    localized_timezone_name: 'Europe/Kiev',
    master_id: 11,
  },
  {
    time_zone_name: 'Jerusalem',
    time_zone_value: 'GMT+02:00',
    localized_timezone_name: 'Asia/Jerusalem',
    master_id: 12,
  },
  {
    time_zone_name: 'Minsk',
    time_zone_value: 'GMT+02:00',
    localized_timezone_name: 'Europe/Minsk',
    master_id: 13,
  },
  {
    time_zone_name: 'Windhoek',
    time_zone_value: 'GMT+02:00',
    localized_timezone_name: 'Africa/Windhoek',
    master_id: 14,
  },
  {
    time_zone_name: 'Athens, Istanbul, Minsk',
    time_zone_value: 'GMT+03:00',
    localized_timezone_name: 'Europe/Istanbul',
    master_id: 15,
  },
  {
    time_zone_name: 'Baghdad',
    time_zone_value: 'GMT+03:00',
    localized_timezone_name: 'Asia/Baghdad',
    master_id: 16,
  },
  {
    time_zone_name: 'Kuwait, Riyadh',
    time_zone_value: 'GMT+03:00',
    localized_timezone_name: 'Asia/Riyadh',
    master_id: 17,
  },
  {
    time_zone_name: 'Moscow, St. Petersburg, Volgograd',
    time_zone_value: 'GMT+03:00',
    localized_timezone_name: 'Europe/Moscow',
    master_id: 18,
  },
  {
    time_zone_name: 'Nairobi',
    time_zone_value: 'GMT+03:00',
    localized_timezone_name: 'Africa/Nairobi',
    master_id: 19,
  },
  {
    time_zone_name: 'Tbilisi',
    time_zone_value: 'GMT+03:00',
    localized_timezone_name: 'Asia/Tbilisi',
    master_id: 20,
  },
  {
    time_zone_name: 'Tehran',
    time_zone_value: 'GMT+03:30',
    localized_timezone_name: 'Asia/Tehran',
    master_id: 21,
  },
  {
    time_zone_name: 'Abu Dhabi, Muscat',
    time_zone_value: 'GMT+04:00',
    localized_timezone_name: 'Asia/Dubai',
    master_id: 22,
  },
  {
    time_zone_name: 'Baku',
    time_zone_value: 'GMT+04:00',
    localized_timezone_name: 'Asia/Baku',
    master_id: 23,
  },
  {
    time_zone_name: 'Baku, Tbilisi, Yerevan',
    time_zone_value: 'GMT+04:00',
    localized_timezone_name: 'Asia/Yerevan',
    master_id: 24,
  },
  {
    time_zone_name: 'Port Louis',
    time_zone_value: 'GMT+04:00',
    localized_timezone_name: 'Indian/Mauritius',
    master_id: 25,
  },
  {
    time_zone_name: 'Kabul',
    time_zone_value: 'GMT+04:30',
    localized_timezone_name: 'Asia/Kabul',
    master_id: 26,
  },
  {
    time_zone_name: 'Ekaterinburg',
    time_zone_value: 'GMT+05:00',
    localized_timezone_name: 'Asia/Yekaterinburg',
    master_id: 27,
  },
  {
    time_zone_name: 'Islamabad, Karachi',
    time_zone_value: 'GMT+05:00',
    localized_timezone_name: 'Asia/Karachi',
    master_id: 28,
  },
  {
    time_zone_name: 'Islamabad, Karachi, Tashkent',
    time_zone_value: 'GMT+05:00',
    localized_timezone_name: 'Asia/Tashkent',
    master_id: 29,
  },
  {
    time_zone_name: 'Chennai, Kolkata, Mumbai, New Delhi',
    time_zone_value: 'GMT+05:30',
    localized_timezone_name: 'Asia/Calcutta',
    master_id: 30,
  },
  {
    time_zone_name: 'Sri Jayawardenepura',
    time_zone_value: 'GMT+05:30',
    localized_timezone_name: 'Asia/Colombo',
    master_id: 31,
  },
  {
    time_zone_name: 'Kathmandu',
    time_zone_value: 'GMT+05:45',
    localized_timezone_name: 'Asia/Katmandu',
    master_id: 32,
  },
  {
    time_zone_name: 'Almaty, Novosibirsk',
    time_zone_value: 'GMT+06:00',
    localized_timezone_name: 'Asia/Novosibirsk',
    master_id: 33,
  },
  {
    time_zone_name: 'Astana, Dhaka',
    time_zone_value: 'GMT+06:00',
    localized_timezone_name: 'Asia/Dhaka',
    master_id: 34,
  },
  {
    time_zone_name: 'Rangoon',
    time_zone_value: 'GMT+06:30',
    localized_timezone_name: 'Asia/Rangoon',
    master_id: 35,
  },
  {
    time_zone_name: 'Bangkok, Hanoi, Jakarta',
    time_zone_value: 'GMT+07:00',
    localized_timezone_name: 'Asia/Bangkok',
    master_id: 36,
  },
  {
    time_zone_name: 'Krasnoyarsk',
    time_zone_value: 'GMT+07:00',
    localized_timezone_name: 'Asia/Krasnoyarsk',
    master_id: 37,
  },
  {
    time_zone_name: 'Beijing, Chongqing, Hong Kong, Urumqi',
    time_zone_value: 'GMT+08:00',
    localized_timezone_name: 'Asia/Shanghai',
    master_id: 38,
  },
  {
    time_zone_name: 'Irkutsk, Ulaan Bataar',
    time_zone_value: 'GMT+08:00',
    localized_timezone_name: 'Asia/Ulaanbaatar',
    master_id: 39,
  },
  {
    time_zone_name: 'Kuala Lumpur, Singapore',
    time_zone_value: 'GMT+08:00',
    localized_timezone_name: 'Asia/Singapore',
    master_id: 40,
  },
  {
    time_zone_name: 'Perth',
    time_zone_value: 'GMT+08:00',
    localized_timezone_name: 'Australia/Perth',
    master_id: 41,
  },
  {
    time_zone_name: 'Taipei',
    time_zone_value: 'GMT+08:00',
    localized_timezone_name: 'Asia/Taipei',
    master_id: 42,
  },
  {
    time_zone_name: 'Osaka, Sapporo, Tokyo',
    time_zone_value: 'GMT+09:00',
    localized_timezone_name: 'Asia/Tokyo',
    master_id: 43,
  },
  {
    time_zone_name: 'Seoul',
    time_zone_value: 'GMT+09:00',
    localized_timezone_name: 'Asia/Seoul',
    master_id: 44,
  },
  {
    time_zone_name: 'Yakutsk',
    time_zone_value: 'GMT+09:00',
    localized_timezone_name: 'Asia/Yakutsk',
    master_id: 45,
  },
  {
    time_zone_name: 'Adelaide',
    time_zone_value: 'GMT+09:30',
    localized_timezone_name: 'Australia/Adelaide',
    master_id: 46,
  },
  {
    time_zone_name: 'Darwin',
    time_zone_value: 'GMT+09:30',
    localized_timezone_name: 'Australia/Darwin',
    master_id: 47,
  },
  {
    time_zone_name: 'Brisbane',
    time_zone_value: 'GMT+10:00',
    localized_timezone_name: 'Australia/Brisbane',
    master_id: 48,
  },
  {
    time_zone_name: 'Canberra, Melbourne, Sydney',
    time_zone_value: 'GMT+10:00',
    localized_timezone_name: 'Australia/Sydney',
    master_id: 49,
  },
  {
    time_zone_name: 'Guam, Port Moresby',
    time_zone_value: 'GMT+10:00',
    localized_timezone_name: 'Pacific/Port_Moresby',
    master_id: 50,
  },
  {
    time_zone_name: 'Hobart',
    time_zone_value: 'GMT+10:00',
    localized_timezone_name: 'Australia/Hobart',
    master_id: 51,
  },
  {
    time_zone_name: 'Vladivostok',
    time_zone_value: 'GMT+10:00',
    localized_timezone_name: 'Asia/Vladivostok',
    master_id: 52,
  },
  {
    time_zone_name: 'Magadan, Solomon Is., New Caledonia',
    time_zone_value: 'GMT+11:00',
    localized_timezone_name: 'Pacific/Guadalcanal',
    master_id: 53,
  },
  {
    time_zone_name: 'Auckland, Wellington',
    time_zone_value: 'GMT+12:00',
    localized_timezone_name: 'Pacific/Auckland',
    master_id: 54,
  },
  {
    time_zone_name: 'Fiji, Kamchatka, Marshall Is.',
    time_zone_value: 'GMT+12:00',
    localized_timezone_name: 'Pacific/Fiji',
    master_id: 55,
  },
  {
    time_zone_name: 'Azores',
    time_zone_value: 'GMT-01:00',
    localized_timezone_name: 'Atlantic/Azores',
    master_id: 56,
  },
  {
    time_zone_name: 'Cape Verde Is.',
    time_zone_value: 'GMT-01:00',
    localized_timezone_name: 'Atlantic/Cape_Verde',
    master_id: 57,
  },
  {
    time_zone_name: 'Mid-Atlantic',
    time_zone_value: 'GMT-02:00',
    localized_timezone_name: 'Etc/GMT+2',
    master_id: 58,
  },
  {
    time_zone_name: 'Brasilia',
    time_zone_value: 'GMT-03:00',
    localized_timezone_name: 'America/Sao_Paulo',
    master_id: 59,
  },
  {
    time_zone_name: 'Buenos Aires',
    time_zone_value: 'GMT-03:00',
    localized_timezone_name: 'America/Buenos_Aires',
    master_id: 60,
  },
  {
    time_zone_name: 'Buenos Aires, Georgetown',
    time_zone_value: 'GMT-03:00',
    localized_timezone_name: 'America/Buenos_Aires',
    master_id: 61,
  },
  {
    time_zone_name: 'Greenland',
    time_zone_value: 'GMT-03:00',
    localized_timezone_name: 'America/Godthab',
    master_id: 62,
  },
  {
    time_zone_name: 'Montevideo',
    time_zone_value: 'GMT-03:00',
    localized_timezone_name: 'America/Montevideo',
    master_id: 63,
  },
  {
    time_zone_name: 'Newfoundland',
    time_zone_value: 'GMT-03:30',
    localized_timezone_name: 'America/St_Johns',
    master_id: 64,
  },
  {
    time_zone_name: 'Atlantic Time (Canada)',
    time_zone_value: 'GMT-04:00',
    localized_timezone_name: 'America/Halifax',
    master_id: 65,
  },
  {
    time_zone_name: 'Georgetown, La Paz, San Juan',
    time_zone_value: 'GMT-04:00',
    localized_timezone_name: 'America/La_Paz',
    master_id: 66,
  },
  {
    time_zone_name: 'Manaus',
    time_zone_value: 'GMT-04:00',
    localized_timezone_name: 'America/Santiago',
    master_id: 67,
  },
  {
    time_zone_name: 'Santiago',
    time_zone_value: 'GMT-04:00',
    localized_timezone_name: 'America/Santiago',
    master_id: 68,
  },
  {
    time_zone_name: 'Caracas',
    time_zone_value: 'GMT-04:30',
    localized_timezone_name: 'America/Caracas',
    master_id: 69,
  },
  {
    time_zone_name: 'Bogota, Lima, Quito',
    time_zone_value: 'GMT-05:00',
    localized_timezone_name: 'America/Bogota',
    master_id: 70,
  },
  {
    time_zone_name: 'Eastern Time (US & Canada)',
    time_zone_value: 'GMT-05:00',
    localized_timezone_name: 'America/New_York',
    master_id: 71,
  },
  {
    time_zone_name: 'Indiana (East)',
    time_zone_value: 'GMT-05:00',
    localized_timezone_name: 'America/Indianapolis',
    master_id: 72,
  },
  {
    time_zone_name: 'Central America',
    time_zone_value: 'GMT-06:00',
    localized_timezone_name: 'America/Guatemala',
    master_id: 73,
  },
  {
    time_zone_name: 'Central Time (US & Canada)',
    time_zone_value: 'GMT-06:00',
    localized_timezone_name: 'America/Chicago',
    master_id: 74,
  },
  {
    time_zone_name: 'Guadalajara, Mexico City, Monterrey',
    time_zone_value: 'GMT-06:00',
    localized_timezone_name: 'America/Mexico_City',
    master_id: 75,
  },
  {
    time_zone_name: 'Saskatchewan',
    time_zone_value: 'GMT-06:00',
    localized_timezone_name: 'America/Regina',
    master_id: 76,
  },
  {
    time_zone_name: 'Arizona',
    time_zone_value: 'GMT-07:00',
    localized_timezone_name: 'America/Phoenix',
    master_id: 77,
  },
  {
    time_zone_name: 'Chihuahua, La Paz, Mazatlan',
    time_zone_value: 'GMT-07:00',
    localized_timezone_name: 'America/Chihuahua',
    master_id: 78,
  },
  {
    time_zone_name: 'Mountain Time (US & Canada)',
    time_zone_value: 'GMT-07:00',
    localized_timezone_name: 'America/Denver',
    master_id: 79,
  },
  {
    time_zone_name: 'Pacific Time (US & Canada)',
    time_zone_value: 'GMT-08:00',
    localized_timezone_name: 'America/Los_Angeles',
    master_id: 80,
  },
  {
    time_zone_name: 'Tijuana, Baja California',
    time_zone_value: 'GMT-08:00',
    localized_timezone_name: 'America/Tijuana',
    master_id: 81,
  },
  {
    time_zone_name: 'Alaska',
    time_zone_value: 'GMT-09:00',
    localized_timezone_name: 'America/Anchorage',
    master_id: 82,
  },
  {
    time_zone_name: 'Hawaii',
    time_zone_value: 'GMT-10:00',
    localized_timezone_name: 'Pacific/Honolulu',
    master_id: 83,
  },
  {
    time_zone_name: 'Midway Island, Samoa',
    time_zone_value: 'GMT-11:00',
    localized_timezone_name: 'Etc/GMT+11',
    master_id: 84,
  },
  {
    time_zone_name: 'International Date Line West',
    time_zone_value: 'GMT-12:00',
    localized_timezone_name: 'Etc/GMT+12',
    master_id: 85,
  },
  {
    time_zone_name: 'Eastern Daylight Time (US & Canada)',
    time_zone_value: 'GMT-04:00',
    localized_timezone_name: 'America/New_York',
    master_id: 86,
  },
  {
    time_zone_name: 'Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    time_zone_value: 'GMT+01:00',
    localized_timezone_name: 'Europe/Budapest',
    master_id: 87,
  },
]
