name: Android

on:   
  push:
    branches: [main]

jobs:
  build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js V16
          uses: actions/setup-node@v1
          with:
              node-version: 16.x
      
        - run: npm ci
      
        - run: ./gradlew assembleRelease
          working-directory: android
          name: Build Android apk(debug)
      
